version: '3'

services:
  discord-bot:
    environment:
      - DEBUG=false
    env_file: 
      - ./.env
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
